version: '3.1'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-database.sh
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
volumes:
  db-data:
