version: "3.3"
services: 
    flask_app: 
        build: .
        ports: 
            - "5000:5000"
        environment: 
            - FLASK_APP=index.py
            - FLASK_ENV=development
        volumes:
            - '.:/FlaskApp'