version: '3.1'

services:

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql      
      - ./my-binlog.cnf:/etc/mysql/mariadb.conf.d/my-binlog.cnf

  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080

volumes:
  db_data: